-- Postgres twin of migrations/0001_identity.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

create table settings (
  "key" text PRIMARY KEY,
  value text NOT NULL,
  updated_at bigint NOT NULL
);

create table users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  username_lower text NOT NULL,
  email text NOT NULL,
  email_lower text NOT NULL,
  display_name text,
  avatar_kind text NOT NULL DEFAULT 'identicon',
  avatar_url text,
  signature text,
  title text,
  location text,
  website text,
  bio text,
  timezone text NOT NULL DEFAULT 'UTC',
  locale text NOT NULL DEFAULT 'en',
  post_count bigint NOT NULL DEFAULT 0,
  topic_count bigint NOT NULL DEFAULT 0,
  reaction_count bigint NOT NULL DEFAULT 0,
  is_admin bigint NOT NULL DEFAULT 0,
  is_moderator bigint NOT NULL DEFAULT 0,
  is_banned bigint NOT NULL DEFAULT 0,
  banned_until bigint,
  ban_reason text,
  is_deleted bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  last_seen_at bigint,
  last_post_at bigint
);

CREATE UNIQUE INDEX users_username_lower ON users (username_lower);

CREATE UNIQUE INDEX users_email_lower ON users (email_lower);

CREATE INDEX users_last_seen ON users (last_seen_at DESC);

CREATE INDEX users_post_count ON users (post_count DESC);

create table user_prefs (
  user_id bigint PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  theme text NOT NULL DEFAULT 'system',
  posts_per_page bigint NOT NULL DEFAULT 20,
  topics_per_page bigint NOT NULL DEFAULT 30,
  show_signatures bigint NOT NULL DEFAULT 1,
  show_avatars bigint NOT NULL DEFAULT 1,
  auto_subscribe bigint NOT NULL DEFAULT 1,
  email_digest text NOT NULL DEFAULT 'instant',
  accepts_pm bigint NOT NULL DEFAULT 1,
  updated_at bigint NOT NULL
);

create table sessions (
  id text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at bigint NOT NULL,
  expires_at bigint NOT NULL,
  last_used_at bigint,
  user_agent text,
  ip_hash text
);

CREATE INDEX sessions_user ON sessions (user_id);

CREATE INDEX sessions_expires ON sessions (expires_at);

create table magic_links (
  token_hash text PRIMARY KEY,
  email_lower text NOT NULL,
  created_at bigint NOT NULL,
  expires_at bigint NOT NULL,
  consumed_at bigint,
  ip_hash text,
  redirect_to text
);

CREATE INDEX magic_links_email ON magic_links (email_lower, created_at DESC);

create table passkeys (
  credential_id text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  public_key text NOT NULL,
  counter bigint NOT NULL DEFAULT 0,
  transports text,
  label text,
  created_at bigint NOT NULL,
  last_used_at bigint
);

CREATE INDEX passkeys_user ON passkeys (user_id);

create table groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  colour text,
  priority bigint NOT NULL DEFAULT 0,
  is_default bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

CREATE UNIQUE INDEX groups_slug ON groups (slug);

create table group_members (
  group_id bigint NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  is_leader bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE INDEX group_members_user ON group_members (user_id);

create table ranks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  min_posts bigint NOT NULL DEFAULT 0,
  is_special bigint NOT NULL DEFAULT 0,
  image_url text,
  colour text
);

CREATE INDEX ranks_min_posts ON ranks (min_posts DESC);

create table api_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  label text,
  scopes text NOT NULL DEFAULT 'read',
  created_at bigint NOT NULL,
  expires_at bigint,
  last_used_at bigint,
  revoked_at bigint
);

CREATE UNIQUE INDEX api_tokens_hash ON api_tokens (token_hash);

CREATE INDEX api_tokens_user ON api_tokens (user_id);

create table device_codes (
  device_code text PRIMARY KEY,
  user_code text NOT NULL,
  public_key text NOT NULL,
  user_id bigint REFERENCES users (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  created_at bigint NOT NULL,
  expires_at bigint NOT NULL,
  approved_at bigint,
  sealed_token text,
  label text
);

CREATE UNIQUE INDEX device_codes_user_code ON device_codes (user_code);
