-- Postgres twin of migrations/0002_board.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

create table forums (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint REFERENCES forums (id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'forum',
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  link_url text,
  icon text,
  colour text,
  position bigint NOT NULL DEFAULT 0,
  is_locked bigint NOT NULL DEFAULT 0,
  is_hidden bigint NOT NULL DEFAULT 0,
  topic_count bigint NOT NULL DEFAULT 0,
  post_count bigint NOT NULL DEFAULT 0,
  last_post_id bigint,
  last_post_at bigint,
  created_at bigint NOT NULL
);

CREATE UNIQUE INDEX forums_slug ON forums (slug);

CREATE INDEX forums_parent ON forums (parent_id, position);

create table forum_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forum_id bigint REFERENCES forums (id) ON DELETE CASCADE,
  group_id bigint NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  can_view bigint,
  can_read bigint,
  can_post bigint,
  can_reply bigint,
  can_edit_own bigint,
  can_delete_own bigint,
  can_attach bigint,
  can_poll bigint,
  can_moderate bigint
);

CREATE UNIQUE INDEX forum_permissions_pair ON forum_permissions (forum_id, group_id);

create table topics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forum_id bigint NOT NULL REFERENCES forums (id) ON DELETE CASCADE,
  user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL,
  kind text NOT NULL DEFAULT 'normal',
  is_locked bigint NOT NULL DEFAULT 0,
  is_hidden bigint NOT NULL DEFAULT 0,
  is_deleted bigint NOT NULL DEFAULT 0,
  is_solved bigint NOT NULL DEFAULT 0,
  solved_post_id bigint,
  view_count bigint NOT NULL DEFAULT 0,
  reply_count bigint NOT NULL DEFAULT 0,
  first_post_id bigint,
  last_post_id bigint,
  last_post_at bigint,
  last_poster_id bigint REFERENCES users (id) ON DELETE SET NULL,
  moved_to_id bigint REFERENCES topics (id) ON DELETE SET NULL,
  bumped_at bigint NOT NULL,
  created_at bigint NOT NULL
);

CREATE INDEX topics_forum_recent ON topics (forum_id, kind DESC, bumped_at DESC);

CREATE INDEX topics_user ON topics (user_id, created_at DESC);

CREATE INDEX topics_recent ON topics (bumped_at DESC);

CREATE UNIQUE INDEX topics_forum_slug ON topics (forum_id, slug);

create table posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id bigint NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
  forum_id bigint NOT NULL REFERENCES forums (id) ON DELETE CASCADE,
  user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  reply_to_id bigint REFERENCES posts (id) ON DELETE SET NULL,
  body text NOT NULL,
  body_format text NOT NULL DEFAULT 'markdown',
  position bigint NOT NULL DEFAULT 0,
  is_hidden bigint NOT NULL DEFAULT 0,
  is_deleted bigint NOT NULL DEFAULT 0,
  edit_count bigint NOT NULL DEFAULT 0,
  edited_at bigint,
  edited_by bigint REFERENCES users (id) ON DELETE SET NULL,
  edit_reason text,
  ip_hash text,
  created_at bigint NOT NULL
);

CREATE INDEX posts_topic ON posts (topic_id, position);

CREATE INDEX posts_user ON posts (user_id, created_at DESC);

CREATE INDEX posts_forum_recent ON posts (forum_id, created_at DESC);

create table post_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  body text NOT NULL,
  body_format text NOT NULL,
  editor_id bigint REFERENCES users (id) ON DELETE SET NULL,
  reason text,
  created_at bigint NOT NULL
);

CREATE INDEX post_revisions_post ON post_revisions (post_id, created_at DESC);

create table reactions (
  post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'like',
  created_at bigint NOT NULL,
  PRIMARY KEY (post_id, user_id, kind)
);

CREATE INDEX reactions_user ON reactions (user_id, created_at DESC);

create table topic_reads (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  topic_id bigint NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
  last_post_id bigint NOT NULL,
  read_at bigint NOT NULL,
  PRIMARY KEY (user_id, topic_id)
);

create table forum_reads (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  forum_id bigint NOT NULL REFERENCES forums (id) ON DELETE CASCADE,
  read_at bigint NOT NULL,
  PRIMARY KEY (user_id, forum_id)
);

create table polls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id bigint NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
  question text NOT NULL,
  max_choices bigint NOT NULL DEFAULT 1,
  change_vote bigint NOT NULL DEFAULT 1,
  hide_results bigint NOT NULL DEFAULT 0,
  closes_at bigint,
  created_at bigint NOT NULL
);

CREATE UNIQUE INDEX polls_topic ON polls (topic_id);

create table poll_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id bigint NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
  label text NOT NULL,
  position bigint NOT NULL DEFAULT 0
);

CREATE INDEX poll_options_poll ON poll_options (poll_id, position);

create table poll_votes (
  poll_id bigint NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
  option_id bigint NOT NULL REFERENCES poll_options (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at bigint NOT NULL,
  PRIMARY KEY (poll_id, option_id, user_id)
);

create table attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES posts (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  filename text NOT NULL,
  mime text NOT NULL,
  size_bytes bigint NOT NULL,
  storage_key text NOT NULL,
  width bigint,
  height bigint,
  checksum text,
  download_count bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

CREATE INDEX attachments_post ON attachments (post_id);

CREATE INDEX attachments_user ON attachments (user_id, created_at DESC);
