-- Postgres twin of migrations/0003_social.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

create table subscriptions (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  target_type text NOT NULL,
  target_id bigint NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (user_id, target_type, target_id)
);

CREATE INDEX subscriptions_target ON subscriptions (target_type, target_id);

create table ignores (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  target_type text NOT NULL,
  target_id bigint NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (user_id, target_type, target_id)
);

create table notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind text NOT NULL,
  actor_id bigint REFERENCES users (id) ON DELETE SET NULL,
  subject_type text,
  subject_id bigint,
  url text,
  title text,
  excerpt text,
  data text,
  dedupe_key text,
  read_at bigint,
  emailed_at bigint,
  created_at bigint NOT NULL
);

CREATE INDEX notifications_user ON notifications (user_id, created_at DESC);

CREATE INDEX notifications_unread ON notifications (user_id, read_at, created_at DESC);

CREATE UNIQUE INDEX notifications_dedupe ON notifications (user_id, dedupe_key)
  WHERE dedupe_key IS NOT NULL AND read_at IS NULL;

create table notification_prefs (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind text NOT NULL,
  in_app bigint NOT NULL DEFAULT 1,
  email bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, kind)
);

create table email_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email text NOT NULL,
  to_user_id bigint REFERENCES users (id) ON DELETE CASCADE,
  subject text NOT NULL,
  html text NOT NULL,
  text text NOT NULL,
  kind text NOT NULL,
  dedupe_key text,
  status text NOT NULL DEFAULT 'pending',
  attempts bigint NOT NULL DEFAULT 0,
  last_error text,
  scheduled_at bigint NOT NULL,
  sent_at bigint,
  created_at bigint NOT NULL
);

CREATE INDEX email_queue_due ON email_queue (status, scheduled_at);

CREATE UNIQUE INDEX email_queue_dedupe ON email_queue (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

create table conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject text NOT NULL,
  created_by bigint REFERENCES users (id) ON DELETE SET NULL,
  last_message_at bigint,
  message_count bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

CREATE INDEX conversations_recent ON conversations (last_message_at DESC);

create table conversation_members (
  conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  last_read_at bigint,
  is_archived bigint NOT NULL DEFAULT 0,
  left_at bigint,
  created_at bigint NOT NULL,
  PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX conversation_members_user ON conversation_members (user_id, is_archived);

create table messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  body text NOT NULL,
  body_format text NOT NULL DEFAULT 'markdown',
  is_deleted bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

CREATE INDEX messages_conversation ON messages (conversation_id, created_at);

create table blocks (
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  blocked_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at bigint NOT NULL,
  PRIMARY KEY (user_id, blocked_id)
);
