-- Postgres twin of migrations/0004_moderation.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

create table reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id bigint REFERENCES users (id) ON DELETE SET NULL,
  target_type text NOT NULL,
  target_id bigint NOT NULL,
  reason text NOT NULL,
  detail text,
  status text NOT NULL DEFAULT 'open',
  handled_by bigint REFERENCES users (id) ON DELETE SET NULL,
  handled_at bigint,
  resolution text,
  created_at bigint NOT NULL
);

CREATE INDEX reports_status ON reports (status, created_at DESC);

CREATE INDEX reports_target ON reports (target_type, target_id);

create table mod_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id bigint REFERENCES users (id) ON DELETE SET NULL,
  action text NOT NULL,
  target_type text,
  target_id bigint,
  forum_id bigint REFERENCES forums (id) ON DELETE SET NULL,
  detail text,
  created_at bigint NOT NULL
);

CREATE INDEX mod_log_recent ON mod_log (created_at DESC);

CREATE INDEX mod_log_target ON mod_log (target_type, target_id);

create table ban_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  pattern text NOT NULL,
  reason text,
  expires_at bigint,
  created_by bigint REFERENCES users (id) ON DELETE SET NULL,
  created_at bigint NOT NULL
);

CREATE INDEX ban_rules_kind ON ban_rules (kind);

create table warnings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  actor_id bigint REFERENCES users (id) ON DELETE SET NULL,
  post_id bigint REFERENCES posts (id) ON DELETE SET NULL,
  points bigint NOT NULL DEFAULT 1,
  reason text NOT NULL,
  expires_at bigint,
  created_at bigint NOT NULL
);

CREATE INDEX warnings_user ON warnings (user_id, created_at DESC);

create table audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  action text NOT NULL,
  target_type text,
  target_id bigint,
  ip_hash text,
  detail text,
  created_at bigint NOT NULL
);

CREATE INDEX audit_events_rate ON audit_events (user_id, action, created_at DESC);

CREATE INDEX audit_events_ip ON audit_events (ip_hash, action, created_at DESC);
