-- Postgres twin of migrations/0008_feed_sources.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

alter table forums add column if not exists member_posting text NOT NULL DEFAULT 'topics';

create table feed_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forum_id bigint NOT NULL REFERENCES forums (id) ON DELETE CASCADE,
  user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  url text NOT NULL,
  title text,
  is_enabled bigint NOT NULL DEFAULT 1,
  interval_minutes bigint NOT NULL DEFAULT 30,
  max_items bigint NOT NULL DEFAULT 10,
  etag text,
  last_modified text,
  fetched_at bigint,
  next_fetch_at bigint,
  last_status text,
  last_error text,
  item_count bigint NOT NULL DEFAULT 0,
  created_by bigint REFERENCES users (id) ON DELETE SET NULL,
  created_at bigint NOT NULL
);

CREATE INDEX feed_sources_forum ON feed_sources (forum_id, id);

CREATE INDEX feed_sources_due ON feed_sources (is_enabled, next_fetch_at);

create table feed_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id bigint NOT NULL REFERENCES feed_sources (id) ON DELETE CASCADE,
  guid text NOT NULL,
  topic_id bigint REFERENCES topics (id) ON DELETE SET NULL,
  link text,
  published_at bigint,
  created_at bigint NOT NULL
);

CREATE UNIQUE INDEX feed_items_guid ON feed_items (source_id, guid);

CREATE INDEX feed_items_topic ON feed_items (topic_id);
