-- Postgres twin of migrations/0009_settings_snapshots.sql (generated with `libsql-pg convert-schema`, then reviewed).
-- INTEGER -> bigint (0/1 flags and epoch-millisecond timestamps stay integers, as the app writes them);
-- INTEGER PRIMARY KEY AUTOINCREMENT -> identity; BLOB -> bytea.

create table settings_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  revision bigint NOT NULL,
  digest text NOT NULL,
  host text,
  version text,
  size bigint NOT NULL,
  body text NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE (user_id, revision)
);

CREATE INDEX settings_snapshots_user ON settings_snapshots (user_id, revision DESC);
